### ISSUE TITLE
'int16_t' does not name a type

### ISSUE THREAD

**Issue by fguptill** [rickkas7/AssetTrackerRK#1]
Veryifing code using this library in Particle Build fails with this error:
```
AssetTrackerRK/LIS3DH.h:20:2: error: 'int16_t' does not name a type
  int16_t  x

I have been using this library with no problem for a few weeks now.  Now suddenly I am getting this error.  It makes no sense to me, as the type int16_t is defined in stdint.h, which is properly included.  What am I missing here?

**Comment by rickkas7** [comment]
Which device (presumably Electron, but just in case) and what system firmware are you targeting? Different device and system versions use different compile farm machines, so there can be a difference or problem that only affects one version.

**Comment by fguptill** [comment]
The device is indeed an Electron.

I'm not sure how to answer your other question.  I have been developing my own ino that uses the Assettracker shield and your excellent library.

I have been successfully compiling this same code for several weeks now, but it suddenly started producing this error yesterday.  I am using a forked version of your library, but I (think I) have not modified it.

Fred

On Nov 10, 2016, at 15:33, rickkas7 <notifications@github.com<mailto:notifications@github.com>> wrote:

Which device (presumably Electron, but just in case) and what system firmware are you targeting? Different device and system versions use different compile farm machines, so there can be a difference or problem that only affects one version.

##

**Comment by fguptill** [comment]
Problem solved
Inserted following text as line 1 in code and it compiles without errors

"// This #include statement was automatically added by the Particle IDE."

Amazing!
